name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 1 * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_TOKEN }}
     - name: Build & Publish Docker Images
       run: |
         for i in $(ls -d */ | cut -f1 -d'/')
         do
            echo "Build & Publish: $i"
            docker build $i/. --progress plain -t krosan89/node-rust:$i && docker push krosan89/node-rust:$i
         done
